Add templates
strapi/community-content pull request #408
Opened 2021-06-02 10:03 UTC by markkaylor

2021-06-02 11:57 UTC, remidej requested changes

2021-06-02 11:57 UTC, remidej commented on templates/README.md
> +![Starters](/assets/banner-starters.png)
I think we should either remove the banner, or create a new one for templates. But mixing the 2 creates confusion

2021-06-02 11:57 UTC, remidej commented on templates/README.md
> +**Generate** the template by running:
It's so nice to see your work on the CLI pay off :)

2021-06-02 11:57 UTC, remidej commented on templates/README.md
> +    - Responsive design using UIkit
This isn't relevant for a backend-only template. Maybe we can highlight something else, like i18n, draft & publish or plugins installed by default

2021-06-02 11:57 UTC, remidej commented on templates/README.md
> +A template is a Strapi project containing existing content-types and data.
Maybe add a link to the docs?

2021-06-02 11:58 UTC, markkaylor commented on templates/README.md
> +![Starters](/assets/banner-starters.png)
yes, oops missed that.  Thanks!

2021-06-02 12:26 UTC, markkaylor commented on templates/README.md
> +    - Responsive design using UIkit
Yeah good catch. What about the other keys?  I removed some others from the starters. I'm wondering if templates should list the starters using them with a github url

2021-06-02 14:53 UTC, remidej commented on templates/README.md
> +    - Responsive design using UIkit
Yes I think that can be useful, especially if we later reference templates on the website, so we can link to the related starters

2021-06-03 13:48 UTC, remidej approved these changes
Looks good :)

2021-06-03 14:33 UTC, merged