Add edgarlr/magazine starter
strapi/community-content pull request #460
Opened 2021-07-23 02:37 UTC by edgarlr

Add magazine starter kit to starters.yml

2021-07-29 07:50 UTC, markkaylor requested changes
Hey @edgarlr 

Thanks so much for submitting your starter and template.  

Could you update your starter to be inside a `starter` directory, and then add a `starter.json` file at the root which points to the template github repo:

```bash
{
  "template": "https://github.com/edgarlr/strapi-template-magazine"
}
```

Take a look at this starter as an example: [https://github.com/strapi/strapi-starter-next-corporate](https://github.com/strapi/strapi-starter-next-corporate)

That way it can be used with the starter CLI:

```bash
npx create-strapi-starter my-starter https://github.com/edgarlr/magazine
```

You can learn more about the starter CLI here: [https://strapi.io/blog/announcing-the-strapi-starter-cli](https://strapi.io/blog/announcing-the-strapi-starter-cli)

2021-07-29 07:50 UTC, markkaylor commented on starters/starters.yml
> +  command:
You should add the starter CLI command here

2021-08-02 02:24 UTC, edgarlr commented
@markkaylor Sure, I'll update this!

2021-08-07 05:47 UTC, edgarlr commented
Hey @markkaylor, I updated the PR, if you want to take a look at it again!

2021-08-10 09:05 UTC, markkaylor requested changes
Looks good, if you don't mind changing the repo and using the shortcut that would be awesome.  Once you have some seed data on the template we can merge.

2021-08-10 09:05 UTC, markkaylor commented on starters/starters.yml
> +    npm: npx create-strapi-starter my-site https://github.com/edgarlr/strapi-starter-magazine
If you change the name of your repo to `strapi-starter-next-magazine` you would be able to use the shortcut here too: `npx create-strapi-starter edgarlr/next-magazine`.

More info at the bottom of this article: https://strapi.io/blog/announcing-the-strapi-starter-cli

2021-08-13 05:54 UTC, edgarlr commented on starters/starters.yml
> +    npm: npx create-strapi-starter my-site https://github.com/edgarlr/strapi-starter-magazine
@markkaylor done! I updated the name of the repository and the commands, and also I already added the seed data on the template!

2021-08-24 06:56 UTC, edgarlr commented
Hey @markkaylor, can you please review this PR again? I already addressed the changes and added the seed data to the template 🙂

2021-08-24 07:15 UTC, markkaylor commented
Hi @edgarlr I think it is good to go, I'll take another look later today to be sure.   It might be a week or two before we can merge.  I'll keep you posted.

2021-08-24 07:20 UTC, edgarlr commented
@markkaylor  Sounds great, thanks! If you could take a look at the other PR as well, that would be great! I'll stay tuned!

2023-01-02 13:20 UTC, closed without merging