Add edgarlr/strapi-template-magazine template
strapi/community-content pull request #461
Opened 2021-07-23 02:45 UTC by edgarlr

Add edgarlr/strapi-template-magazine to templates.yml

2021-07-29 07:48 UTC, markkaylor requested changes

2021-07-29 07:48 UTC, markkaylor commented on templates/templates.yml
> +    npm: npx create-strapi-app my-app-name --template https://github.com/edgarlr/strapi-template-magazine
You can use a shortcut for the repo.  https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/installation/templates.html#using-a-template
```suggestion
    yarn: yarn create strapi-app my-app-name --template edgarlr/magazine
    npm: npx create-strapi-app my-app-name --template edgarlr/magazine
```

2021-07-29 08:02 UTC, markkaylor commented
If you could add seed data that would be awesome.  The process isn't really documented but you can see how it is done here: https://github.com/strapi/strapi-template-blog/blob/master/template/config/functions/bootstrap.js. Let me know if you have any questions.

2021-08-02 02:22 UTC, edgarlr commented
@markkaylor Sure, I'll try to add seed data!

2021-08-13 05:53 UTC, edgarlr commented
Hey @markkaylor, I just added the seed data! can you review it again?

2023-01-02 13:19 UTC, closed without merging